### ISSUE TITLE
kbcon 佈局適用於 Filco Minila 嗎？

### ISSUE THREAD

**Issue by erstern** [rime/rime-combo-pinyin#1]
請問，kbcon 佈局是否適用於 Minila 這種空格旁邊就有 Fn 鍵的鍵盤？
之前對 AMJ 不瞭解，而且早就想叫 Minila 充實後宮，kbcon 可用麼？

**Comment by lotem** [comment]
沒仔細研究過 Minila，因爲適應不了下排字母的偏移。
那兩個 Fn 鍵可以隨便改麼？如果只能做 Fn，那就沒法利用了。
方案裏假設左邊拇指控「;」鍵。如果沒有這個按鍵，也可以用 QWERTY 鍵盤的「A」鍵代替。我平常在筆記本和其他鍵盤上就是這麼用的，差別不大。可能因爲我左手小指平時就用得多，整天用他並擊 Control 鍵（換到 Caps Lock 的位置）。

**Comment by erstern** [comment]
那應該是不中了。
我也沒實際試過 Minila，看用過的發帖、還有簡介說，Fn 應該只能組合當方向鍵以及 Ins、Home 這些，或是嫌 Space 短當作擴展部分。都不是用家能自定義的。
我還是先鑽研方案吧。

**Comment by lotem** [comment]
綜上所述，不能在 Minila 上用左手拇指擊出 H 聲母。
但還可以用 PC 兼容鍵位，即左手小指擊 H'。
