### ISSUE TITLE
Feature Request:重复敲击输入

### ISSUE THREAD

**Issue by shituniao** [rime/rime-combo-pinyin#11]
参考多数软件中快捷键的用法，例如：
按Ctrl+Z执行撤销时，若按住Ctrl键不松开，连续敲击Z键，则可以重复执行多次撤销。
是否有可能实现按住声母按键不松，连续敲击韵母按键，可以重复打出多个同声母汉字。
例如：按住 h 键不松开，连续敲击 a 键，可重复打出多个 ha

**Comment by LEOYoon-Tsaw** [comment]
那些功能鍵是mask，本來就是按著不放的，沒有可比性
