### ISSUE TITLE
映射 enter 键

### ISSUE THREAD

**Issue by lisu60** [rime/rime-combo-pinyin#3]
我的键盘左右拇指键是空格，右手拇指是 enter 键。希望能够在不更改该布局的前提下使用 kbcon 方案，请问是否有可能在配置中映射 enter 键？可以的话应该如何写配置文件？

**Comment by lotem** [comment]
我做過類似嘗試，因為舊有程序裏的並擊組合是用字符串表示的，這需要前端做一些按鍵到字符的轉換。
https://github.com/rime/squirrel/commit/997f15396615de4a3f65e5595ce1f5edf75263a1
其他前端可能還不支持用非字符按鍵輸入。
後來我放棄了這個用法，因為一個純粹的輸入法無法實現單擊 Enter 鍵時仍持行回車的功能——單擊或並擊的判斷是滯後的，而系統給輸入法的接口只能輸出文字（因而使用空格鍵可行）而不能發送功能鍵。那樣一來，使 Enter 鍵參與輸入的意義就不存在了。

**Comment by lisu60** [comment]
感谢解答，我尝试一下兼容式布局好了

**Comment by lotem** [comment]
既然拇指鍵不能在並擊模式下用作 ENTER，我最終選定的實現方法是在鍵盤上設置一個並擊模式，在拇指位放一個字符鍵，另設一個 ENTER 鍵。
我的佈局裏是左手拇指，你可以改一下並擊的規則，保留空格鍵在左側，因為 `H` 恰好是聲母，可以設定為單擊 `H`/空格鍵出空格，`H+E` 出拼音 he。

**Comment by lisu60** [comment]
是说我应该在键盘上设置一个并击模式，把右手拇指设置成字符键（比如分号）。然后在 Rime 的配置里把左手拇指（空格）映射为 `H`、把右手拇指（分号）映射为 `A`，这样吗？

**Comment by lotem** [comment]
@lisu60 已提交。我覺得這個方案可能對大家有用。
https://github.com/rime/rime-combo-pinyin/blob/master/combo_pinyin_kbcon_left.schema.yaml

不過在 PC 鍵盤上用小指擊 `;` 指法不太方便。
且實測 macbook 鍵盤 `;` 鍵不能和 `j, k, (l)` 並擊（ian, iang）。
所以基本上只適合特製的鍵盤。

**Comment by lisu60** [comment]
感谢，目前已更近并正在试用该“左式键盘控”方案。我的键盘是 Truly Ergonomic 229，没发现键冲突问题
