### ISSUE TITLE
候选出现错乱

### ISSUE THREAD

**Issue by HesperusArcher** [rime/rime-combo-pinyin#4]
不知道该如何准确描述我遇到的问题，姑且称为错乱。

例如，我打「以」多次以后，按「jkl」即「ying」，第一候选就不再是「应」，而是「以」。

这种问题在多个拼写组合都出现过，不仅是「yi」和「ying」，之前都随手`C-k`删掉了，有印象的几个都是同声母，或者是拼写中前几个字母相同，比如「xiang」候选中「下」出现在第一个，别的规律尚未发现。

我用的方案是在宫保拼音（设为默认简体）的基础上，加入了某一`prefix`引导的繁体全拼，和另一形码方案。

我分别注释掉`engine`下的`segmentors`和`translators`中对应的全拼和形码方案，问题依旧。

可以给个思路吗？该如何尝试解决？谢谢！

**Comment by lotem** [comment]
這種現象通常是部署過程中出錯， `*.prism.bin` 和 `*.table.bin` 文件沒有同步更新。
請先查看日誌定位錯誤。

**Comment by lotem** [comment]
應該不是宮保拼音（原裝）配置的問題，錯誤可能存在於本項目之外，如用戶自定義配置或輸入法程序。因此關閉工單。

**Comment by HesperusArcher** [comment]
確實是某個詞庫沒有生成`.table.bin`文件，把我的配置每個部分都試過以後發現是自定義詞庫的問題，可能是某個新加入的詞條的`漢字    pin xie`對應關係出了問題，才沒有正確部署。刪除了最近添加的部分，就正常了。
