### ISSUE TITLE
当前版本在 u 相关的拼音有些蹩脚 

### ISSUE THREAD

**Issue by netwjx** [rime/rime-combo-pinyin#5]
在输入

- wan wen
- guan
- gun qun shun xun zhun zun

u 和 -n 相关的要用 右手食指前伸 和 中指后缩

有什么方便点的方式么?

**Comment by lotem** [comment]
存在這個問題。目前沒有替代的指法。我的對策是勤剪指甲少打字。
也許能改到 `H` 鍵？
還有個不成熟的想法：像手寫（斜體或流線型）速記那樣，把鍵盤傾斜，逆時針轉15度左右。不知有沒有幫助。
