### ISSUE TITLE
选用Control, Shift, Ctrl参与并击的功能无法工作

### ISSUE THREAD

**Issue by zhanghaozhecn** [rime/rime-combo-pinyin#6]
选用控制键参与并击的功能似乎已失效。
以下是宫保拼音键盘控式中启用的注释
__patch:
  # 打開下列註釋行之一，選定左手拇指 H 鍵
  - combo_pinyin_kbcon.options:/if_use_control
  # - combo_pinyin_kbcon.options:/if_use_alt
启用后重新部署，CTRL键无法参与并击。

**Comment by zhanghaozhecn** [comment]
系统版本
![image](https://user-images.githubusercontent.com/72417945/101259243-b1095b80-36f5-11eb-95d5-8a4102432cf7.png)

**Comment by lotem** [comment]
很高兴有您跟进宫保拼音的进展。
这些按键无法工作应该是输入法程序还没有更新。

**Comment by zhanghaozhecn** [comment]
谢谢，期待您的下一次更新。

**Comment by lotem** [comment]
如果需要试用新版，可以从[测试频道](https://bintray.com/rime/weasel/testing)取得自动构建的测试版。
