### ISSUE TITLE
靠并击打不出 'm-a'

### ISSUE THREAD

**Issue by poorich** [rime/rime-combo-pinyin#7]
在小狼毫挂上的 `combo_pinyin.schema.yaml`
想打出 '[ma]' 但失败了，按规则应当并击 `c+v + space` （`f+b + a`），但按下后只显示 '[me]' 而非 '[ma]'
经过多次试验，想打出 '[ma]' 得 按下 `c+v` -> 按下 `space`  -> 松开 `c+v`，这太复杂了
其他 '声母-a' 能正常并击打出
——————————
另有个小问题
想打 'n-eng' 'ch-eng' 'd-eng'
应该按下 `声母 + k+l`，我尝试按下声母后又并击 `k+l` 出不来 '-eng'，得分开按 `k` `l` 方可，这些许的间隔让流畅感有所降低
输入 'sh-eng' 'zh-eng' 't-eng' 'l-eng' 等则无此现象

**Comment by lotem** [comment]
​大概是硬件性能問題。可以測試一下不開輸入法能否可靠地輸出以上並擊組合。如果不能，則該鍵盤無法用於並擊輸入。

**Comment by poorich** [comment]
经测试，的确是硬件有问题
切身感受到教程中所言『一把好键盘』的重要性
