### ISSUE TITLE
并击音节被拆分问题

### ISSUE THREAD

**Issue by tusooa** [rime/rime-combo-pinyin#8]
例如，并击输入「xian」，在候选词中出现「西安」（大约在第十几个候选里）。而输入「tiang」则由于字典中并无念tiang之字，首选便是「踢昂」。此时按一次backspace，只能删除ang而不能删除ti。

有无解法防止单次并击之音节被再度拆分？

**Comment by lotem** [comment]
有。
切分算法會窮舉音節的可能組合，可以改寫所有音節使有歧義的組合不成立，如將隔音符號添加在每個音節末尾，成為拼寫的一部分而不是當作音節之間的分隔符。
